# Generated by Django 4.1.6 on 2023-02-08 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField()),
                ('displayName', models.CharField(max_length=70)),
                ('github', models.URLField(unique=True)),
                ('profileImage', models.URLField(unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
