# Generated by Django 4.1.6 on 2023-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_profileimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['host'], name='host_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['displayName'], name='displayName_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['github'], name='github_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['profileImage'], name='profileImage_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['username'], name='username_idx'),
        ),
    ]
