# Generated by Django 4.1.6 on 2023-02-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_created_author_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='app.author'),
        ),
    ]
