# Generated by Django 4.1.6 on 2023-02-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_author_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_requests', to='app.author'),
        ),
    ]
