# Generated by Django 4.1.6 on 2023-02-15 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_author_sent_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150, unique=True)),
                ('source', models.URLField(unique=True)),
                ('origin', models.URLField(unique=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(choices=[('markdown', 'text/markdown'), ('plain', 'text/plain'), ('image-png', 'image/png'), ('image-jpeg', 'image/jpeg')], max_length=18)),
                ('content', models.TextField()),
                ('categories', models.TextField()),
                ('comments_url', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private'), ('FRIENDS', 'friends')], max_length=7)),
                ('unlisted', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='app.author')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_posts', to='app.author')),
            ],
        ),
    ]
