# Generated by Django 4.1.6 on 2023-02-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_post_receiver_post_receivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(),
        ),
    ]
