# Generated by Django 4.1.6 on 2023-02-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_post_description_alter_post_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
