# Generated by Django 4.1.7 on 2023-03-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_post_comments_url'),
        ('app', '0015_remove_inbox_post_remove_inbox_type_inbox_date_like_and_more'),
    ]

    operations = [
    ]
