# Generated by Django 4.1.7 on 2023-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20230302_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
