# Generated by Django 4.1.7 on 2023-03-02 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20230302_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('markdown', 'text/markdown'), ('plain', 'text/plain'), ('image-png', 'image/png'), ('image-jpeg', 'image/jpeg')], default='plain', max_length=18),
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
