# Generated by Django 4.1.7 on 2023-03-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_author_confirmed'),
        ('app', '0018_alter_comment_contenttype'),
    ]

    operations = [
    ]
