# Generated by Django 4.1.7 on 2023-03-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20230303_1640'),
        ('app', '0020_alter_post_content_type'),
    ]

    operations = [
    ]
